ALTER EVENT autoupdate1 DISABLE;
drop event autoupdate1;
ALTER EVENT autoupdate2 DISABLE;
drop event autoupdate2;
ALTER EVENT autoupdate3 DISABLE;
drop event autoupdate3;
ALTER EVENT autoupdate4 DISABLE;
drop event autoupdate4;
ALTER EVENT autoupdate5 DISABLE;
drop event autoupdate5;
ALTER EVENT autoupdate6 DISABLE;
drop event autoupdate6;
ALTER EVENT autoupdate7 DISABLE;
drop event autoupdate7;
ALTER EVENT autoupdate8 DISABLE;
drop event autoupdate8;
ALTER EVENT autoupdate9 DISABLE;
drop event autoupdate9;
ALTER EVENT autoupdate10 DISABLE;
drop event autoupdate10;
ALTER EVENT autoupdate11 DISABLE;
drop event autoupdate11;
ALTER EVENT autoupdate12 DISABLE;
drop event autoupdate12;
ALTER EVENT autoupdate13 DISABLE;
drop event autoupdate13;
ALTER EVENT autoupdate14 DISABLE;
drop event autoupdate14;
ALTER EVENT autoupdate15 DISABLE;
drop event autoupdate15;
ALTER EVENT autoupdate16 DISABLE;
drop event autoupdate16;
ALTER EVENT autoupdate17 DISABLE;
drop event autoupdate17;
ALTER EVENT autoupdate18 DISABLE;
drop event autoupdate18;
ALTER EVENT autoupdate19 DISABLE;
drop event autoupdate19;
ALTER EVENT autoupdate20 DISABLE;
drop event autoupdate20;
ALTER EVENT autoupdate21 DISABLE;
drop event autoupdate21;
ALTER EVENT autoupdate22 DISABLE;
drop event autoupdate22;
ALTER EVENT autoupdate23 DISABLE;
drop event autoupdate23;
ALTER EVENT autoupdate24 DISABLE;
drop event autoupdate24;
ALTER EVENT autoupdate25 DISABLE;
drop event autoupdate25;
ALTER EVENT autoupdate26 DISABLE;
drop event autoupdate26;
ALTER EVENT autoupdate27 DISABLE;
drop event autoupdate27;
ALTER EVENT autoupdate28 DISABLE;
drop event autoupdate28;
ALTER EVENT autoupdate29 DISABLE;
drop event autoupdate29;
ALTER EVENT autoupdate30 DISABLE;
drop event autoupdate30;
ALTER EVENT autoupdate31 DISABLE;
drop event autoupdate31;
ALTER EVENT autoupdate32 DISABLE;
drop event autoupdate32;
ALTER EVENT autoupdate33 DISABLE;
drop event autoupdate33;
ALTER EVENT autoupdate34 DISABLE;
drop event autoupdate34;
ALTER EVENT autoupdate35 DISABLE;
drop event autoupdate35;
ALTER EVENT autoupdate36 DISABLE;
drop event autoupdate36;
ALTER EVENT autoupdate37 DISABLE;
drop event autoupdate37;
ALTER EVENT autoupdate38 DISABLE;
drop event autoupdate38;
ALTER EVENT autoupdate39 DISABLE;
drop event autoupdate39;
ALTER EVENT autoupdate40 DISABLE;
drop event autoupdate40;
ALTER EVENT autoupdate41 DISABLE;
drop event autoupdate41;
ALTER EVENT autoupdate42 DISABLE;
drop event autoupdate42;
ALTER EVENT autoupdate43 DISABLE;
drop event autoupdate43;
ALTER EVENT autoupdate44 DISABLE;
drop event autoupdate44;
ALTER EVENT autoupdate45 DISABLE;
drop event autoupdate45;
ALTER EVENT autoupdate46 DISABLE;
drop event autoupdate46;
ALTER EVENT autoupdate47 DISABLE;
drop event autoupdate47;
ALTER EVENT autoupdate48 DISABLE;
drop event autoupdate48;
ALTER EVENT autoupdate49 DISABLE;
drop event autoupdate49;
ALTER EVENT autoupdate50 DISABLE;
drop event autoupdate50;
ALTER EVENT autoupdate51 DISABLE;
drop event autoupdate51;
ALTER EVENT autoupdate52 DISABLE;
drop event autoupdate52;
ALTER EVENT autoupdate53 DISABLE;
drop event autoupdate53;
ALTER EVENT autoupdate54 DISABLE;
drop event autoupdate54;
ALTER EVENT autoupdate55 DISABLE;
drop event autoupdate55;
ALTER EVENT autoupdate56 DISABLE;
drop event autoupdate56;
ALTER EVENT autoupdate57 DISABLE;
drop event autoupdate57;
ALTER EVENT autoupdate58 DISABLE;
drop event autoupdate58;
ALTER EVENT autoupdate59 DISABLE;
drop event autoupdate59;
ALTER EVENT autoupdate60 DISABLE;
drop event autoupdate60;
ALTER EVENT autoupdate61 DISABLE;
drop event autoupdate61;
ALTER EVENT autoupdate62 DISABLE;
drop event autoupdate62;
ALTER EVENT autoupdate63 DISABLE;
drop event autoupdate63;
ALTER EVENT autoupdate64 DISABLE;
drop event autoupdate64;
ALTER EVENT autoupdate65 DISABLE;
drop event autoupdate65;
ALTER EVENT autoupdate66 DISABLE;
drop event autoupdate66;
ALTER EVENT autoupdate67 DISABLE;
drop event autoupdate67;
ALTER EVENT autoupdate68 DISABLE;
drop event autoupdate68;
ALTER EVENT autoupdate69 DISABLE;
drop event autoupdate69;
ALTER EVENT autoupdate70 DISABLE;
drop event autoupdate70;
ALTER EVENT autoupdate71 DISABLE;
drop event autoupdate71;
ALTER EVENT autoupdate72 DISABLE;
drop event autoupdate72;
ALTER EVENT autoupdate73 DISABLE;
drop event autoupdate73;
ALTER EVENT autoupdate74 DISABLE;
drop event autoupdate74;
ALTER EVENT autoupdate75 DISABLE;
drop event autoupdate75;
ALTER EVENT autoupdate76 DISABLE;
drop event autoupdate76;
ALTER EVENT autoupdate77 DISABLE;
drop event autoupdate77;
ALTER EVENT autoupdate78 DISABLE;
drop event autoupdate78;
ALTER EVENT autoupdate79 DISABLE;
drop event autoupdate79;
ALTER EVENT autoupdate80 DISABLE;
drop event autoupdate80;
ALTER EVENT autoupdate81 DISABLE;
drop event autoupdate81;
ALTER EVENT autoupdate82 DISABLE;
drop event autoupdate82;
ALTER EVENT autoupdate83 DISABLE;
drop event autoupdate83;
ALTER EVENT autoupdate84 DISABLE;
drop event autoupdate84;
ALTER EVENT autoupdate85 DISABLE;
drop event autoupdate85;
ALTER EVENT autoupdate86 DISABLE;
drop event autoupdate86;
ALTER EVENT autoupdate87 DISABLE;
drop event autoupdate87;
ALTER EVENT autoupdate88 DISABLE;
drop event autoupdate88;
ALTER EVENT autoupdate89 DISABLE;
drop event autoupdate89;
ALTER EVENT autoupdate90 DISABLE;
drop event autoupdate90;
ALTER EVENT autoupdate91 DISABLE;
drop event autoupdate91;
ALTER EVENT autoupdate92 DISABLE;
drop event autoupdate92;
ALTER EVENT autoupdate93 DISABLE;
drop event autoupdate93;
ALTER EVENT autoupdate94 DISABLE;
drop event autoupdate94;
ALTER EVENT autoupdate95 DISABLE;
drop event autoupdate95;
ALTER EVENT autoupdate96 DISABLE;
drop event autoupdate96;
ALTER EVENT autoupdate97 DISABLE;
drop event autoupdate97;
ALTER EVENT autoupdate98 DISABLE;
drop event autoupdate98;
ALTER EVENT autoupdate99 DISABLE;
drop event autoupdate99;
ALTER EVENT autoupdate100 DISABLE;
drop event autoupdate100;
